version: "3.7"

services:
  database_pg_rentx:
    image: postgres
    container_name: database_pg_rentx
    restart: always
    ports:
      - 5432:5342
    environment:
      - POSTGRES_USER=xcall
      - POSTGRES_PASSWORD=1324
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
